version: "3.8"

volumes:
  mysql_data:

networks:
  betting_network:  # Новое имя сети

services:
  betting_db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 121212
      MYSQL_DATABASE: betting_db
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"
    networks:
      - betting_network  # Обновленное имя сети

  betting:
    restart: always
    build: ./backend
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - betting_db
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://betting_db:3306/betting_db'
      SPRING_DATASOURCE_USERNAME: 'root'
      SPRING_DATASOURCE_PASSWORD: '121212'
      JAVA_OPTS: '-Xmx512m'
    networks:
      - betting_network  # Обновленное имя сети

  frontend:
    build: ./frontend
    ports:
      - "127.0.0.1:3000:80"
    depends_on:
      - betting
    networks:
      - betting_network  # Обновленное имя сети
